### ISSUE TITLE
Can't run or build unity project with CAS package installed for any platform except 'iOS' and 'Android' 

### ISSUE THREAD

**Issue by maximkornilov** [cleveradssolutions/CAS-Unity#1]
When any platform except 'iOS' and 'Android' (for example like "PC, Mac & Linux Standalone" or WebGL) is selected in Build Settings, after importing the CAS package to Your Project, you will get the following  compiler error:

```
Library\PackageCache\com.cleversolutions.ads.unity@546484f78f\Editor\CASEditorUtils.cs(108,17): error CS0103: The name 'CASPreprocessBuild' does not exist in the current context
```

CAS package version: 2.7.3

### Possible solutions:
The menu item in `CASEditorUtils.cs` should be wrapped inside the same preprocessor directives as CASPreprocessBuild class:
```
#if UNITY_ANDROID || UNITY_IOS || CASDeveloper
```

**Comment by Jedures** [comment]
We are fixed it in CAS 2.8.1.
