### ISSUE TITLE
Can't run or build unity project with CAS package with FamiliesAds "on" in 'Android' platform

### ISSUE THREAD

**Issue by AlexTake** [cleveradssolutions/CAS-Unity#4]
Can't run or build unity project with CAS package with FamiliesAds "on" in 'Android' platform
I`m using your example project.
How to reproduce:
1. Enable FamiliesAds.
2. Advertiser ID permission "Removed".
3. JDK, NDK, SDK, Gradle - default from unity.
4. Target API Level - 34
5. Start build
Result
![1](https://github.com/cleveradssolutions/CAS-Unity/assets/48610867/107b1367-9609-4be6-9dc1-adebcbff4049)
![2](https://github.com/cleveradssolutions/CAS-Unity/assets/48610867/be407ade-3960-4cd4-9217-65438f0eaf85)

**Comment by Str4tos** [comment]
Hello, @AlexTake 

We are aware of this issue. 
I assume you are using Unity 2020 or an older version; please correct me if I'm mistaken. 
Unfortunately, due to reasons unknown to us, DT Exchange cannot be built for API 34 on an outdated version of Gradle Android Plugin. We have been in communication with Digital Turbine regarding this matter, but they have not provided a solution.

We can suggest three possible solutions to address this issue:

1. Upgrade to Unity 2022.3 or a newer version, which uses Gradle 7.
2. Temporarily lower the target API to 33.
3. Temporarily remove DT Exchange from the build. To do this, disable the Families Ads Solution and add the network adapters you wish to include in the build.

Thank you for your feedback.

Best regards,
Denis

**Comment by AlexTake** [comment]
Hi, @Str4tos thanks for the quick response. I tried the first two options and still get the same error.![image](https://github.com/cleveradssolutions/CAS-Unity/assets/48610867/edd7f682-dff7-46ce-9c9d-a795a6f3d9bb)
In the first option I used unity 2022.3.11f1
I also tried building on gradle version 8.3
The build is successful as soon as I disable Families ads. Disabling this policy does not suit us. 
If I didn’t understand option 3 correctly, can you describe it in more detail?

**Comment by Str4tos** [comment]
We should take a closer look at your environment.

#### Firstly
> In the first option I used unity 2022.3.11f1
> I also tried building on gradle version 8.3

Please share the text of all build errors you are encountering with Unity 2023.3.  
We have information that the issue shown in your first post does not occur with Unity 2023.3.

Your screenshot only shows an issue with Gradle initialization, which is likely related to the lack of support for Gradle Android Plugin 8.3.  
In Unity, you don't have the option to select the Gradle Android Plugin version without changing the path to a compatible Gradle Build Tools version. Therefore, it's recommended to use only the Gradle versions that are distributed with the Unity Editor.

#### Secondly
> 2. Temporarily lower the target API to 33.  

Have you tried building by lowering the target Android API from 34 to 33 (Android 13)?  
If so, could you please share the build errors you encountered in text format?

We are confident that the issue you described does not occur when using API 33, regardless of the Unity version.

#### And finally
> The build is successful as soon as I disable Families ads. Disabling this policy does not suit us.
> If I didn’t understand option 3 correctly, can you describe it in more detail?

Please be aware that the `Families Ads` checkbox is just an easy way to add recommended network adapters for designed for families apps. You have the option to not use `Families Ads` checkbox and include ad network adapters individually.

> 3. Temporarily remove DT Exchange from the build. To do this, disable the Families Ads Solution and add the network adapters you wish to include in the build.

To do it in Unity Editor follow the steps:
1. Open `Assets > CleverAdsSolutions > Android Settings`.
2. Select the `Audience` for Children, which is the requirement for DFF Apps.
3. Expand the Adapters section. You will see which adapters are enabled when you check `Families Ads`.
4. Now you can uncheck `Families Ads` and include the available ad network adapters, except for the problematic `DT Exchange`.

Best regards,
Denis
