### ISSUE TITLE
Issues Building in Unity 6000.0.1f1

### ISSUE THREAD

**Issue by AndrewKahr** [cleveradssolutions/CAS-Unity#6]
The plugin cannot build for Android after updating to Unity 6000.0.1f1 as it has upgraded to gradle plugin version 8.3.0 which removed `android.enableDexingArtifactTransform=false` and replaced it with `android.useFullClasspathForDexingTransform=true`. Even after making this change the build will fail stating that a namespace needs to be defined for the `CASPlugin.androidlib`. It seems the library is defining the namespace in the `AndroidManifest.xml` which is no longer supported in 8.3.0 and instead needs to be defined in the library's build.gradle. This was done on a fresh project in 6000.0.1f1 after following the setup instructions in the wiki.

**Comment by Str4tos** [comment]
Hi @AndrewKahr, thank you for raising the issue.

We will work on compatibility of our plugin for Unity 6 and notify you as soon as possible.

**Comment by Starksky** [comment]
Hi, the same mistake

**Comment by AndrewKahr** [comment]
The fix appears to be working. Thanks so much for the fix!
