### ISSUE TITLE
Seems layout is broken here -> https://github.com/cleveradssolutions/CAS-Unity/wiki/Configuring-SDK#select-ad-formats-to-use

### ISSUE THREAD

**Issue by sergei201613** [cleveradssolutions/CAS-Unity#9]
![image](https://github.com/cleveradssolutions/CAS-Unity/assets/29472685/0c35e939-94b3-433b-9df2-12e6063f9d1a)

**Comment by Str4tos** [comment]
Hi @sergei201613, thank you for raising the issue.  
The Wiki page has already been corrected.
